### PR TITLE
Add option to set custom wireguard network range

### PR DESCRIPTION
**Pull request by hat3ph**
Add option to set custom wireguard network range or use the default 10.7.0.0 range

### CODE REVIEW

**Comment by hwdsl2** [comment]
@hat3ph Hello! First, thank you for contributing!

This is not a common use case, as for most users, setting a custom WireGuard network range is not needed because they can just use the default `10.7.0.0/24`. It is tricky to get this feature right, for example, when asking users to enter a network range, we would want them to specify it in CIDR format, e.g. `10.7.0.0/24`, instead of just `10.7.0.0`. We also need to check to make sure it's a valid CIDR, and that it is a private IP address range.

Considering the complexity vs. benefits, I would prefer not to merge this at this time. But you are welcome to adapt the project to your needs, according to the license.

**Comment by hat3ph** [comment]
How about if I refine the custom VPN network range to only accept private IP range?

https://github.com/hat3ph/wireguard-install/commit/80d1cffda3abd140e119c635bb8b0e62d4b7d691

**Comment by hwdsl2** [comment]
Thanks for making the changes. As I said this feature is not commonly used and the complexity might outweigh the benefits to users. You're welcome to adapt this project to your needs, however.

**Comment by hat3ph** [comment]
Noted. Just that I feel that my changes give move flexibility to users to customize their VPN setup instead of manually edit the script to change the network range.

**Comment by bpossolo** [comment]
I would find this useful as well because would like to use a different network from `10.7.0.0/24`

**Comment by e1970180** [comment]
Could you please add this option?
I would find it useful when I need to configure access to several VPN servers from one router.
P.S. Even the option to select one octet would be enough for this while keeping it simple.

**Pull request closed without merging**
